POST https://localhost:7159/conversation
Content-Type: application/json
{
  "messages": [
    {
      "id": "12345",
      "role": "user",
      "content": "give me a list of patients with influenza",
      "date": "2024-07-15T19:13:12.943Z"
    }
  ]
}

###

POST https://localhost:7159/search?query="hello%20world"
Content-Type: application
