POST https://localhost:7159/conversation
Content-Type: application/json
{
  "messages": [
    {
      "id": "12345",
      "role": "user",
      "content": "find a list of patients with influenza in the notes",
      "date": "2024-07-15T19:13:12.943Z"
    }
  ]
}